### ISSUE TITLE
[Bug] Runtime error on Resolution of DID Document without previousMessageId

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#246]
## Bug description
Briefly describe the bug.

Rust throws a runtime error when resolving a DID that has multiple messages in which at least one does not have a previousMessageId when it supposed to. 

## Language version
What programming language are you using? Rust or one of the bindings?
Which version of the language are you running?

- Language: WASM
- Version: 0.2.2

## IOTA Identity version
Which version of IOTA Identity are you using?

- Version (version number, commit, or branch): 

(Branch from dev, merged in fix/wasm-example)
feat/improve-js-examples

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

## Errors
Paste any errors that you see, including logs, errors, or screenshots.

```
Err > RuntimeError: memory access out of bounds
    at dlmalloc::dlmalloc::Chunk::size::hf82636e8b1c5762b (<anonymous>:wasm-function[4197]:0x2bcfb3)
    at __rdl_realloc (<anonymous>:wasm-function[762]:0x1d31af)
    at __rust_realloc (<anonymous>:wasm-function[3752]:0x2bb4f6)
    at __wbindgen_realloc (<anonymous>:wasm-function[3576]:0x2b9f07)
    at passStringToWasm0 (identity.rs_branch2\bindings\wasm\node\identity_wasm.js:89:15)
    at module.exports.resolve (identity.rs_branch2\bindings\wasm\node\identity_wasm.js:256:16)
    at resolution (identity.rs_branch2\bindings\wasm\examples\resolution.js:13:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (identity.rs_branch2\bindings\wasm\examples\node_2.js:23:20)
```

**Comment by JelleMillenaar** [comment]
My bad, made a wrong assumption and its actually just a unclear WASM error for you provided incorrect input.

**Comment by l1h3r** [comment]
Issue for better WASM errors: https://github.com/iotaledger/identity.rs/issues/146
